version: '3'
services:
  web:
    build:
      context: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver"
    ports:
     - "7001:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app


  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - dt-data: /var/lib/postgresql/data


  redis:
    image: redis:7
    volumes:
      - redis_data:/data
  celery:
    biuld:
      context: .
    command: celery -A shop_api worker --loglever=info
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app


  celery_beat:
    biuld:
      context: .
    command: celery -A shop_api beat --loglever=info
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

  flower:
    biuld:
      context: .
    command: celery -A shop_api flower --port=5555
    ports:
      - '5555:5555'
    depends_on:
      - redis
      - celery
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  db-data:
  redis_data:
